sonar.projectKey=fiap-mecanica-os-service
sonar.projectName=FiapMecanica OS Service

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
